/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNewChatRouteImport } from './routes/_authenticated/new-chat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats.index'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'
import { Route as AuthenticatedJoinTokenRouteImport } from './routes/_authenticated/join.$token'
import { Route as AuthenticatedGroupGroupIdRouteImport } from './routes/_authenticated/group.$groupId'
import { Route as AuthenticatedChatsUserIdRouteImport } from './routes/_authenticated/chats.$userId'
import { Route as AuthenticatedCallUserIdRouteImport } from './routes/_authenticated/call.$userId'

const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewChatRoute = AuthenticatedNewChatRouteImport.update({
  id: '/new-chat',
  path: '/new-chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJoinTokenRoute = AuthenticatedJoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupGroupIdRoute =
  AuthenticatedGroupGroupIdRouteImport.update({
    id: '/group/$groupId',
    path: '/group/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsUserIdRoute =
  AuthenticatedChatsUserIdRouteImport.update({
    id: '/chats/$userId',
    path: '/chats/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCallUserIdRoute = AuthenticatedCallUserIdRouteImport.update({
  id: '/call/$userId',
  path: '/call/$userId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/new-chat': typeof AuthenticatedNewChatRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/call/$userId': typeof AuthenticatedCallUserIdRoute
  '/chats/$userId': typeof AuthenticatedChatsUserIdRoute
  '/group/$groupId': typeof AuthenticatedGroupGroupIdRoute
  '/join/$token': typeof AuthenticatedJoinTokenRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/new-chat': typeof AuthenticatedNewChatRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/call/$userId': typeof AuthenticatedCallUserIdRoute
  '/chats/$userId': typeof AuthenticatedChatsUserIdRoute
  '/group/$groupId': typeof AuthenticatedGroupGroupIdRoute
  '/join/$token': typeof AuthenticatedJoinTokenRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/new-chat': typeof AuthenticatedNewChatRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/call/$userId': typeof AuthenticatedCallUserIdRoute
  '/_authenticated/chats/$userId': typeof AuthenticatedChatsUserIdRoute
  '/_authenticated/group/$groupId': typeof AuthenticatedGroupGroupIdRoute
  '/_authenticated/join/$token': typeof AuthenticatedJoinTokenRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/complete-profile'
    | '/admin'
    | '/new-chat'
    | '/settings'
    | '/call/$userId'
    | '/chats/$userId'
    | '/group/$groupId'
    | '/join/$token'
    | '/u/$username'
    | '/chats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/complete-profile'
    | '/admin'
    | '/new-chat'
    | '/settings'
    | '/call/$userId'
    | '/chats/$userId'
    | '/group/$groupId'
    | '/join/$token'
    | '/u/$username'
    | '/chats'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/complete-profile'
    | '/_authenticated/admin'
    | '/_authenticated/new-chat'
    | '/_authenticated/settings'
    | '/_authenticated/call/$userId'
    | '/_authenticated/chats/$userId'
    | '/_authenticated/group/$groupId'
    | '/_authenticated/join/$token'
    | '/_authenticated/u/$username'
    | '/_authenticated/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-chat': {
      id: '/_authenticated/new-chat'
      path: '/new-chat'
      fullPath: '/new-chat'
      preLoaderRoute: typeof AuthenticatedNewChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/join/$token': {
      id: '/_authenticated/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof AuthenticatedJoinTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/group/$groupId': {
      id: '/_authenticated/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/$userId': {
      id: '/_authenticated/chats/$userId'
      path: '/chats/$userId'
      fullPath: '/chats/$userId'
      preLoaderRoute: typeof AuthenticatedChatsUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/call/$userId': {
      id: '/_authenticated/call/$userId'
      path: '/call/$userId'
      fullPath: '/call/$userId'
      preLoaderRoute: typeof AuthenticatedCallUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedNewChatRoute: typeof AuthenticatedNewChatRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedCallUserIdRoute: typeof AuthenticatedCallUserIdRoute
  AuthenticatedChatsUserIdRoute: typeof AuthenticatedChatsUserIdRoute
  AuthenticatedGroupGroupIdRoute: typeof AuthenticatedGroupGroupIdRoute
  AuthenticatedJoinTokenRoute: typeof AuthenticatedJoinTokenRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedNewChatRoute: AuthenticatedNewChatRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedCallUserIdRoute: AuthenticatedCallUserIdRoute,
  AuthenticatedChatsUserIdRoute: AuthenticatedChatsUserIdRoute,
  AuthenticatedGroupGroupIdRoute: AuthenticatedGroupGroupIdRoute,
  AuthenticatedJoinTokenRoute: AuthenticatedJoinTokenRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CompleteProfileRoute: CompleteProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
